import type { Metadata } from "next";
import "./globals.css";
import { interFont } from "../../styles/fonts";
import classNames from "classnames";
import { ThemeProvider } from "@material-tailwind/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(interFont.className, "bg-primary-grey")}>
        {children}
      </body>
    </html>
  );
}
